### PR TITLE
WIP: clickable text

### PR DESCRIPTION
**Pull request by TomyLobo**
excuse the halos around the fake mouse cursor, I was lazy

That's an actual tooltip, indicating the command that will be run when you click the line.
Clickable elements so far:
- "coords" lines
- "sum blocks/players" entries
- page arrows

Implementation is done using an HTML-like XML subset as an intermediate layer.
The language is parsed using jaxb and is described here:
https://bukkit.atlassian.net/browse/BUKKIT-5245

Contains code from CraftBukkit o.b.c, which is licensed under the LGPL. (or maybe GPL - that isn't clear from their repo)

### CODE REVIEW

**Comment by frymaster** [comment]
@TomyLobo how easy would it be to alter this so the XML is translated into JSON so it can be sent using ``getServer().dispatchCommand(getConsoleSender(),"minecraft:tellraw " + player + " " + someJSONtext);`` rather than via NMS code?

I'd like to avoid using NMS and other non-compatible means if possible

My current intention is to merge this, #566, and a better completely plain output method and give the user the option, depending on context and overridable by the command

e.g. It might use json text for in-game clients, plain text for rcon or dumping to file, and colored text for the console, by default

**Comment by nightpool** [comment]
@frymaster Bukkit itself is an inherently non-compatible means at this point. 

Sponge has rich text support.

**Comment by md-5** [comment]
@nightpool uh, so does Spigot

**Comment by nightpool** [comment]
Sure. Just commented on the project I knew about.

**Comment by Brokkonaut** [comment]
I will close this as outdated, but if someone wants to update it it might be a nice feature

**Pull request closed without merging**
