### PR TITLE
Worldedit version check

### LINKED ISSUE #584: Error on startup if legacy version of WorldEdit installed
We should detect this and provide a friendlier error

````
2015-02-23 10:17:15 [ERROR] Error occurred while enabling LogBlock v1.92 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.worldedit.WorldEdit.getEventBus()Lcom/sk89q/worldedit/util/eventbus/EventBus;
        at de.diddiz.worldedit.WorldEditLoggingHook.hook(WorldEditLoggingHook.java:52) ~[?:?]
        at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:120) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-e81edfc]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
````

### PR DESCRIPTION
**Pull request by Mahagon**
that should fix #584

Testet with WE 5

And WE 6 + WE 6 Snapshot

### CODE REVIEW

**Comment by Mahagon** [comment]
@frymaster try catch NoSuchMethodError would be possible to.
dont know what you prefer

**Comment by LefsFlare** [comment]
No offense but your fix appears to have some English errors.

Failed too hook into WorldEdit. Your Version seems to be outdated. Please use at least WorldEdit 6.

Failed to hook into WorldEdit. Your WorldEdit version seems to be outdated, please make sure WorldEdit is at least version 6.

**Comment by Mahagon** [comment]
sry for that im not a native english speaker.
i replaced that msg with your example

**Comment by frymaster** [comment]
Committed in 1cb32d26ed614e14c7844922397274112bb8d985

**Pull request closed without merging**
