### PR TITLE
fire, fireball and sign logging

### PR DESCRIPTION
**Pull request by Mahagon**
just a view changes for 1.8 :)

### CODE REVIEW

**Comment by frymaster** [comment]
You also need to update the minimum bukkit API version in pom.xml to 1.7.2-R0.3 as the fireball API didn't exist in R0.2 - that's why the travis build is failing (probably not failing for you because you have a local copy that's more up to date)

**Comment by frymaster** [comment]
Similarly, the metrics commit is because you're building against a higher version of the bukkit API than we (currently) need to - no reason to restrict older servers until we use the newer features

**Comment by frymaster** [comment]
I'm willing to admit I'm derping with this, but can you confirm that ghast fireballs destroying e.g. netherrack is recorded with these changes?  It wasn't, for me

**Comment by Mahagon** [comment]
oh im using the 1.8 bukkit api atm 

i dont think that metrics are that important, i reverted my changes for metrics 

Here are three screens to confirm that fire, sign and fireball logging is working :D
http://i.imgur.com/ETMAuss.png
http://i.imgur.com/KgWZF7p.png
http://i.imgur.com/EvnE2WJ.png

Hm but Travis seems to hate me D:

**Comment by frymaster** [comment]
what version/type of server are you on?  Wither fireballs and the fire extinguishing fix (thanks!) are working for me, it's specifically ghasts...

**Comment by frymaster** [comment]
OK, figured out my derp.  That was the first time I'd been to the nether on my test work, and there was about 7500 LavaFlow events in the queue clogging things up :D (my test world is run from my desktop but uses my colo server for SQL, so the4 consumer runs slow at the best of times)

Confirmed ghast fireball logging works

**Comment by Mahagon** [comment]
sry about that import stuff^^ 
Forgot about that :O

**Comment by frymaster** [comment]
Changes committed.

Thanks!

**Pull request closed without merging**
