### PR TITLE
Update to 1.13

### PR DESCRIPTION
**Pull request by Brokkonaut**
I updated it to 1.13

- Full support of BlockData, no more ids
- Import of 1.12 block changes
- Inventory changes are now saved with enchantments etc

### CODE REVIEW

**Comment by md-5** [comment]
How well tested?
Do you want to take over maintenance of this plugin?

**Comment by Brokkonaut** [comment]
Block placement/breaking/manipulation logging and rollback/redo is very much tested with many block types and block states. Database upgrading worked well for our database with about 14 million entries.

Chest inventory modifications, kill logging and chat logging are tested & working too, but as we don't use those features on our server I do not have that much test data available.

Yes, I think I could take over the maintenance of the plugin. I have a long experience in plugin programming and I really want to keep this plugin alive.

**Comment by HeyBanditoz** [comment]
I will be testing this on a small-sized 1.13 survival server.

**Comment by HeyBanditoz** [comment]
Cannot build. `[ERROR] Failed to execute goal on project logblock: Could not resolve dependencies for project de.diddiz:logblock:jar:1.13-SNAPSHOT: Failed to collect dependencies at com.sk89q.worldedit:worldedit-core:jar:7.0.0-SNAPSHOT: Failed to read artifact descriptor for com.sk89q.worldedit:worldedit-core:jar:7.0.0-SNAPSHOT: Could not transfer artifact com.sk89q.worldedit:worldedit-core:pom:7.0.0-SNAPSHOT from/to repobo-snap (http://repo.bukkit.org/content/groups/public): repo.bukkit.org: Unknown host repo.bukkit.org -> [Help 1]`

**Comment by HeyBanditoz** [comment]
The .jars must be placed in the root of the logblock directory, right?

**Comment by Brokkonaut** [comment]
No, you have to install them to your maven repository: https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

The better way is to build WorldEdit yourself `gradlew clean build install` in your local worldedit git repository (be sure to check out the correct branch)

**Pull request merged**
